name: flutter_app
description: A Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  cloudbase_flutter: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.3
  http_mock_adapter: ^0.6.1

flutter:
  uses-material-design: true
